### ISSUE TITLE
Update main website look

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden.io#1]
# Acceptance criteria

* The new logo is used: https://github.com/rancher/project-assets/tree/master/logos
* The new hugo template is used: https://github.com/rancherlabs/projects-theme
* The new color palette is used: https://github.com/rancher/project-assets/blob/master/colors/colors.md

**Comment by ereslibre** [comment]
Working on it on https://github.com/ereslibre/kubewarden.io

Visible at https://ereslibre.github.io/kubewarden.io/

Primary icon etc are not shown due to the path not being the root path, and an issue  with the template being used. However, the content is readable.

This is waiting comments from the rest of the team regarding the contents of the page. It also addresses https://github.com/kubewarden/kubewarden.io/issues/4 partially (there is a link, but no explicit text about the Policy Hub).

**Comment by ereslibre** [comment]
Done. Live at https://kubewarden.io. We can revisit later if we want to tweak some colors or text.
